name: Docker Image CI & API client

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set version
      run: |
        echo "VERSION=$(date +%Y.%-m.%-d.%-H%M)" >> $GITHUB_ENV
        echo "Version: $(date +%Y.%-m.%-d.%-H%M)"
    
    - name: Tag commit
      run: |
        git tag v$VERSION ${{ github.sha }}
        git push origin v$VERSION
            
    - name: Docker login
      run: docker login ghcr.io -u Rene-Sackers -p ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ghcr.io/rene-sackers/vattenfall-dynamic-price-api:$VERSION -t ghcr.io/rene-sackers/vattenfall-dynamic-price-api:latest
      
    - name: Build the API client
      run: |
        docker compose -f compose-gen-client.yaml up --build --abort-on-container-exit
        docker compose -f compose-gen-client.yaml down
      
    - name: Pack the API client
      run: dotnet pack ./src/VattenfallDynamicPriceApi.ApiClient/VattenfallDynamicPriceApi.ApiClient.csproj -c Release -p:PackageVersion=$VERSIO --output ./nuget
      
    - name: Push docker image
      run: docker push --all-tags ghcr.io/rene-sackers/vattenfall-dynamic-price-api
      
    - name: Push API client
      run: dotnet nuget push ./nuget/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/Rene-Sackers/index.json --skip-duplicate --no-symbols